### ISSUE TITLE
Proficiency bug

### ISSUE THREAD

**Issue by jkuo9** [Adalbar3333/Lets_get_to_Equiping#2]
Whenever I run !equip armor shield it tells me my character is not proficient with a shield even though I’m running a hexblde

**Comment by Adalbar3333** [comment]
Hey. Do you mind messaging me on Discord? `@Adalbär#3333`
I just want to see if you have your subclass set up and whatnot. Otherwise, I'll add in the update.

**Comment by Adalbar3333** [comment]
Resolved via Discord
