### ISSUE TITLE
No subclass

### ISSUE THREAD

**Issue by richterdavid** [Adalbar3333/Lets_get_to_Equiping#3]
### What is the Issue?
What is the source of the issue?

Requires a subclass

### How can I reproduce it? 
2nd level ranger, no subclass

```
!equip armor shield
```

### Error Message: 

```py
Traceback (most recent call last):
  Line 38, col 13
    subclasses = load_json(get('subclass'))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Possible Solutions:

Check for absence of subclass

**Comment by Adalbar3333** [comment]
Do you utilize `!level`?

Subclass should be set up via a cvar. I will update the code to not require any subclass. 

Give me an hour to fix it. Go ahead and PM me on discord - "Adalbar#3333"

**Comment by Adalbar3333** [comment]
It's been updated.
